resolver: lts-21.25

packages:
- kantour-core
- kantour-cli

extra-deps:
- shower-0.2.0.3
- hip-1.5.6.0
- repa-3.4.2.0
- git: https://github.com/Javran/union-find.git
  commit: 303e897af1dbea0f19906ceb054ef65bba58606c

