resolver: nightly-2025-12-30

packages:
- kantour-core
- kantour-cli

extra-deps:
- repa-3.4.2.0
- git: https://github.com/Javran/union-find.git
  commit: 303e897af1dbea0f19906ceb054ef65bba58606c
- aeson-picker-0.1.0.6
notify-if-no-run-tests: false

allow-newer: true
allow-newer-deps:
- aeson-picker
