name: kantour-cli
version: 0.2.0.0
synopsis: Javran's KanColle Toolset.
github: Javran/kantour
license: BSD3
author: "Javran Cheng"
maintainer: "Javran.C@gmail.com"
copyright: "Copyright: (c) 2016-Present Javran Cheng"
category: Web

ghc-options:
  - -Wall
  - -Wno-incomplete-uni-patterns

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingVia
  - EmptyCase
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoUnicodeSyntax
  - NumericUnderscores
  - OverloadedStrings
  - PartialTypeSignatures
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeSynonymInstances

dependencies:
- SHA
- aeson
- aeson-pretty
- async
- attoparsec
- base
- bytestring
- case-insensitive
- containers
- diagrams-core
- diagrams-lib
- diagrams-rasterific
- filepath
- hexml
- hip
- http-client
- http-client-tls
- http-date
- http-types
- hxt
- json
- lens
- linear
- math-functions
- mono-traversable
- mtl
- mwc-random
- pretty
- primitive
- random
- safe-exceptions
- shower
- statistics
- template-haskell
- text
- time
- union-find
- unordered-containers
- vector
- vector-algorithms
- writer-cps-mtl
- yaml

library:
  source-dirs: src
  dependencies:
    - kantour-core

executables:
  kantour:
    source-dirs: mains
    main: Main.hs
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Main
    dependencies:
      - kantour-cli
