name: kantour-core
version: 0.2.0.0
synopsis: Core library for KanColle-related tools.
github: Javran/kantour
license: BSD3
author: "Javran Cheng"
maintainer: "Javran.C@gmail.com"
copyright: "Copyright: (c) 2016-Present Javran Cheng"
category: Web

dependencies:
- aeson
- aeson-pretty
- attoparsec
- base
- bytestring
- case-insensitive
- containers
- diagrams-core
- diagrams-lib
- diagrams-rasterific
- filepath
- hexml
- hip
- http-client
- http-client-tls
- http-types
- hxt
- json
- lens
- linear
- math-functions
- mono-traversable
- mtl
- mwc-random
- pretty
- primitive
- random
- statistics
- template-haskell
- text
- unordered-containers
- vector
- vector-algorithms
- yaml

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -O2

tests:
  hspec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - kantour-core
      - hspec
      - QuickCheck
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
