name: kantour-core
version: 0.2.0.0
synopsis: Core library for KanColle-related tools.
github: Javran/kantour
license: BSD3
author: "Javran Cheng"
maintainer: "Javran.C@gmail.com"
copyright: "Copyright: (c) 2016-Present Javran Cheng"
category: Web

dependencies:
- base

data-files:
- data/api_start2.json.xz

library:
  source-dirs: src
  dependencies:
    - aeson
    - containers
    - text
    - vector
    - unordered-containers
    - deriving-aeson
    - lzma
    - bytestring

  ghc-options:
    - -Wall
    - -O2

tests:
  hspec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - kantour-core
      - hspec
      - QuickCheck
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
