name: Continuous Integration
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    name: ci
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: 'GitHub actions env workaround'
        run: 'echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV'

      - uses: actions/checkout@v2

      - name: Setup system dependencies
        run: sudo apt install -y liblzma-dev

      - name: Setup Stack
        uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.0.2'
          enable-stack: true
          stack-version: 'latest'

      - name: Cache Key
        id: cache_key
        run: echo ::set-output name=key::$(md5sum stack.yaml | awk '{print $1}')

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ matrix.os }}-${{ steps.cache_key.outputs.key }}

      - name: Build Snapshot
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          stack --install-ghc --no-interleaved-output --no-terminal test --only-snapshot

      - name: Build dependencies
        run: stack --no-interleaved-output --no-terminal build --test --only-dependencies

      - run: stack --interleaved-output --no-terminal build --test
